name: sahas_api DEV Deployment

on:
    push:
        branches:
            - dev_abhishek
    

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Preparing SSH
              run: sudo apt-get install -y sshpass

            - name: SSH Deployment
              run: |
                  sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@46.202.164.212 << 'EOF'
                    set -e
                    cd /root/sahas/dev
                    DIR="sahas_api"
                    if [ ! -d "$DIR" ]; then
                      echo "Fetching Source - $DIR"
                      git clone --branch dev_abhishek https://github.com/rocketstriker999/$DIR
                    fi
                    cd "$DIR"
                    if [ -f process.id ]; then
                      pid=$(cat process.id)
                      if ps -p $pid > /dev/null; then
                        echo "Terminating $DIR - pid $pid"
                        kill -9 $pid
                      fi
                    fi
                    git checkout dev_abhishek
                    npm install

                    if [ ! -d "logs" ]; then
                      mkdir logs
                    fi
                    nohup node app.js > logs/process.log 2>&1 &
                    new_pid=$!
                    echo "Starting $DIR - pid $new_pid"
                    echo $new_pid > process.id
                    echo "Deployed & Disconnecting SSH"
                    exit 0
                  EOF
