<<<<<<< HEAD
name: sahas_api Production Deployment
=======
name: Remote Server Management
>>>>>>> origin/dev

on:
    push:
        branches:
<<<<<<< HEAD
            - main
=======
            - dev
>>>>>>> origin/dev

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Preparing SSH
              run: sudo apt-get install -y sshpass

            - name: SSH Deployment
              run: |
                  sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@46.202.164.212 << 'EOF'
                    set -e
<<<<<<< HEAD
                    cd /root/prod
                    DIR="sahas_api"
                    if [ ! -d "$DIR" ]; then
                      echo "Fetching Source - $DIR"
                      git clone --branch main https://github.com/rocketstriker999/sahas_api
=======
                    cd /root/dev
                    DIR="sahas_api"
                    if [ ! -d "$DIR" ]; then
                      echo "Fetching Source - $DIR"
                      git clone https://github.com/rocketstriker999/sahas_api
>>>>>>> origin/dev
                    fi
                    cd "$DIR"
                    if [ -f process.id ]; then
                      pid=$(cat process.id)
                      if ps -p $pid > /dev/null; then
                        echo "Terminating $DIR - pid $pid"
                        kill -9 $pid
                      fi
                    fi
<<<<<<< HEAD
                    git pull origin
                    npm install
                    nohup node app.js > process.log 2>&1 &
                    new_pid=$!
                    echo "Starting sahas_api - pid $new_pid"
=======
                    git pull origin dev
                    npm install
                    nohup node app.js > process.log 2>&1 &
                    new_pid=$!
                    echo "Starting $DIR - pid $new_pid"
>>>>>>> origin/dev
                    echo $new_pid > process.id
                    echo "Deployed & Disconnecting SSH"
                    exit 0
                  EOF
